---
- name: "Delete invalid DNS resolve file"
  file:
    state: absent
    path: "{{ common.resolv.default }}"
  
- name: "Link to proper DNS resolve file"  
  file:
    src: "{{ common.resolv.systemd }}"
    dest: "{{ common.resolv.default }}"
    state: link

- name: Install aptitude using apt
  apt: 
    name: aptitude
    state: latest 
    update_cache: yes
    force_apt_get: yes

- name: Install packages that allow apt to be used over HTTPS
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common