---
- name: Initialize the Kubernetes cluster using kubeadm
  command: kubeadm init --apiserver-advertise-address="192.168.50.10" --apiserver-cert-extra-sans="192.168.50.10"  --node-name k8s-master --pod-network-cidr=192.168.0.0/16

- name: Create kubeconfig directory if it does not exist
  file:
    path: /home/vagrant/.kube
    state: directory
    mode: '0755'

- name: Copy a "kubeconfig" file from admin
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/vagrant/.kube/config
    owner: vagrant
    group: vagrant
    remote_src: yes

- name: Install calico pod network
  become: false
  command: kubectl apply -f https://docs.projectcalico.org/v3.9/manifests/calico.yaml

- name: Fix issue with Calico and Ubuntu 19.04 Network
  command: 'kubectl -n kube-system set env daemonset/calico-node FELIX_IGNORELOOSERPF=true'
  become: false

- name: Generate join command
  command: kubeadm token create --print-join-command
  register: join_command

- name: Copy join command to local file
  local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="/tmp/join-command"
  become: false
  run_once: true