---
- name: Wait for Jenkins to start up before proceeding.
  command: >
    curl -D - --silent --max-time 5 http://{{ jenkins_hostname }}:{{ jenkins_http_port }}{{ jenkins_url_prefix }}/cli/
  args:
    warn: false
  register: result
  until: >
    (result.stdout.find("403 Forbidden") != -1)
    or (result.stdout.find("200 OK") != -1)
    and (result.stdout.find("Please wait while") == -1)
  retries: "{{ jenkins_connection_retries }}"
  delay: "{{ jenkins_connection_delay }}"
  changed_when: false
  check_mode: false
  
- name: Get Jenkins XSRF Crumb token
  uri:
    url: 'http://{{ jenkins_hostname }}:{{ jenkins_http_port }}{{ jenkins_url_prefix }}/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,":",//crumb)'
    user: "{{jenkins_admin_username}}"
    password: "{{jenkins_admin_password}}"
    method: GET
    force_basic_auth: yes
    return_content: yes
  register: jenkins_seesion_crumb
  retries: 3
  delay: 2

- name: Configure Jenkins Job [Training CI] 
  uri:
    url: "http://{{ jenkins_hostname }}:{{ jenkins_http_port }}{{ jenkins_url_prefix }}/createItem?name=Training-CI"
    user: "{{jenkins_admin_username}}"
    password: "{{jenkins_admin_password}}"
    force_basic_auth: yes
    method: POST
    body: "{{ lookup('file', 'templates/training-job-ci.xml') }}"
    headers:
      Jenkins-Crumb: "{{ jenkins_seesion_crumb.content.split(':')[1] }}"
      Content-Type: "text/xml"
    status_code: [200,201]
    body_format: raw
  retries: 3
  delay: 2

- name: Configure Jenkins Job [Training CD] 
  uri:
    url: "http://{{ jenkins_hostname }}:{{ jenkins_http_port }}{{ jenkins_url_prefix }}/createItem?name=Training-CD"
    user: "{{jenkins_admin_username}}"
    password: "{{jenkins_admin_password}}"
    force_basic_auth: yes
    method: POST
    body: "{{ lookup('file', 'templates/training-job-cd.xml') }}"
    headers:
      Jenkins-Crumb: "{{ jenkins_seesion_crumb.content.split(':')[1] }}"
      Content-Type: "text/xml"
    status_code: [200,201]
    body_format: raw
  retries: 3
  delay: 2